@url=http://localhost:5135
###
POST {{url}}/slots
Content-Type: application/json
Authorization: Bearer 

{
    "Time" : "24/07/2023 03:00 pm",
    "Cost":100,
    "DoctorId" :"6307d003-d75e-49a0-a742-f2dbc3a4cb4a",
    "DoctorName":"Dr. Andy",
    "IsReserved" : false
}

###
POST  {{url}}/appointments
Content-Type: application/json
Authorization: Bearer 

{
    "SlotId": "0a514ad9-7cfd-43dd-9540-af492300d06a",
    "PatientName":"Patient A2"
}
//Authentication APIs
###
POST  {{url}}/login
Content-Type: application/json

{
    "Username": "admin"
}
###
POST  {{url}}/login/Doctor
Content-Type: application/json

{
    "Username": "Dr. Andy"
}
###
POST  {{url}}/login/Patient
Content-Type: application/json

{
    "Username": "Patient A"
}

//Get Slots, Appointments, doctors and patient lists APIs
###
GET  {{url}}/slots
Authorization: Bearer 
DocId: 

###
GET {{url}}/appointments
Authorization: Bearer 
DocId:

###
GET {{url}}/slots/Available
Authorization: Bearer
###
GET {{url}}/UserManagement/GetDoctors
Authorization: Bearer 
###
GET {{url}}/UserManagement/GetPatients
Authorization: Bearer 